### PR TITLE
endpoint/logic adjustment - back in working state

### PR DESCRIPTION
**Pull request by appatalks**
- Grabbing data from ```https://query1.finance.yahoo.com/v8/finance/chart```

I had changed quite a bit during a :cloud_with_lightning_and_rain: night. 
Very :sleepy: but wanted to get something out working just for fun :penguin: 

I really love the original code so I tried to get it to match as best as I can in terms of feel.
Likely :bug: :cricket: :fly: here and there, and better ways to do this :sweat_smile: 

Screenshot from 2023-08-13 21-09-34

### CODE REVIEW

**Comment by appatalks** [comment]
Oh I should note, I didn't test during market hours yet. Not certain if I have the right field for the change of price and %.

**Comment by pcause** [comment]
can you add support for NOCOLOR

**Comment by TimoFrancke-cnic** [comment]
@appatalks can you add some detection for python vs python3? I tried running this on MacOS and I had to change lines 57 and 58 to "python3". Alternatively, use just bash Printf for the formatting?

**Comment by appatalks** [comment]
@TimoFrancke-cnic I'll see what I can do, please allow me a few days to play with it :)

@pcause
For WSL issue, I am afraid I am not have much success getting my windows & hardware to work with it in general to effectively troubleshoot :(

**Review by appatalks — COMMENTED** [review]
Don't use this yet. For some reason the change % is rounding.
I'm trying to figure it out :)

**Review by appatalks — COMMENTED** [review]
Working now :)

**Comment by lm2lm2** [comment]
hello
is it possible to make it work back? :)

**Comment by pstadler** [comment]
Please see https://github.com/pstadler/ticker.sh/issues/45#issuecomment-1801809146

**Pull request closed without merging**
